language: java
sudo: false
install: true
group: deprecated-2017Q4
addons:
  sonarcloud:
    organization: dfalessi-github
    token:
      secure: 7a592cabc85375feae1dc87ba7605a18b9873060
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
